### ISSUE TITLE
Reset of Picture files doesn't work

### ISSUE THREAD

**Issue by CO2-Pool** [dieBaerigenBerchtesgadener/PlOtter#1]
Hi, thank you very much for this great project. This really made my day, finally a web frontend for my brachiograph, and even the accuracy of drawing is improved. Well done, thank you!
But there is a minor issue. Once I have loaded a picture and it was drawn, it is drawn again, even If I have chosen / uploaded a new picture. I have to reboot the pi to accept a new picture, it is not possible to draw several different pictures one after another, because always the first picture is drawn again, even if I have uploaded and transformed another one (the transformation is shown accurately on the web frontend, but the following drawing is from the picture before). I hope you see what I mean. I would be very happy if this issue could be solved.
Thanks a lot and best regards.

**Comment by dieBaerigenBerchtesgadener** [comment]
So far we know that reloading the website in your browser should help.

**Comment by dieBaerigenBerchtesgadener** [comment]
Fixed
